package Entities;
// Generated 16-nov-2016 18:31:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {


     private Integer idPlayer;
     private Team team;
     private String name;
     private BigDecimal weight;
     private BigDecimal height;

    public Player() {
    }

    public Player(Team team, String name, BigDecimal weight, BigDecimal height) {
       this.team = team;
       this.name = name;
       this.weight = weight;
       this.height = height;
    }
   
    public Integer getIdPlayer() {
        return this.idPlayer;
    }
    
    public void setIdPlayer(Integer idPlayer) {
        this.idPlayer = idPlayer;
    }
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }




}


