package Entities;
// Generated 16-nov-2016 18:31:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team  implements java.io.Serializable {


     private Integer idTeam;
     private String name;
     private String city;
     private Set players = new HashSet(0);

    public Team() {
    }

	
    public Team(String name, String city) {
        this.name = name;
        this.city = city;
    }
    public Team(String name, String city, Set players) {
       this.name = name;
       this.city = city;
       this.players = players;
    }
   
    public Integer getIdTeam() {
        return this.idTeam;
    }
    
    public void setIdTeam(Integer idTeam) {
        this.idTeam = idTeam;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getPlayers() {
        return this.players;
    }
    
    public void setPlayers(Set players) {
        this.players = players;
    }




}


